# copy_oc_client.yml
---
- name: Create a temp dir
  command: mktemp -d -t ansible.XXXXXXXXXX
  register: temp_output

- name: Set tmp_path
  set_fact:
    tmp_path: "{{ temp_output.stdout }}"

- name: Download mac client
  get_url:
    url: "https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-mac.zip"
    dest: "{{ tmp_path }}/oc.zip"
  when: ansible_os_family == 'Darwin'

- name: Download win client
  get_url:
    url: "https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-windows.zip"
    dest: "{{ tmp_path }}/oc.zip"
  when: ansible_os_family == 'Windows'

- name: Download linux client
  get_url:
    url: "https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz"
    dest: "{{ tmp_path }}/oc.tar.gz"
  when: ansible_os_family != 'Darwin' and ansible_os_family != 'Windows'

- name: Unzip client
  unarchive:
    src: "{{ tmp_path }}/oc.zip"
    dest: "{{ tmp_path }}"
    mode: 0755
    remote_src: yes
  when: ansible_os_family == 'Darwin' or ansible_os_family == 'Windows'

- name: Untar client
  unarchive:
    src: "{{ tmp_path }}/oc.tar.gz"
    dest: "{{ tmp_path }}"
    mode: 0755
    remote_src: yes
  when: ansible_os_family != 'Darwin' and ansible_os_family != 'Windows'

- name: Copy oc client
  shell: "cp {{ tmp_path }}/*/oc {{ openshift_client_dest }} && chmod 755 {{ openshift_client_dest }}/oc"

- name: Remove the temp directory
  file:
    path: "{{ tmp_path }}"
    state: absent
